resilience4j:
  retry:
    instances:
      inventoryRetry:
        max-attempts: 3
        wait-duration: 5s

  ratelimiter:
    instances:
      inventoryrateLimiter:
        limit-for-period: 5
        limit-refresh-period: 2
        timeout-duration:
          2s
  circuitbreaker:
    instances:
      inventoryCircuitBreaker:
        register-health-indicator: true
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 5
        automatic-transition-from-open-to-half-open-enabled: true

